name: Build

on:
  push:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Dar permisos a Gradle
        run: chmod +x gradlew

      - name: Compilar mod
        run: ./gradlew build --no-daemon

      - name: Guardar archivo JAR
        uses: actions/upload-artifact@v4
        with:
          name: Sinestro-Boss
          path: build/libs/*.jar
          if-no-files-found: error
